### ISSUE TITLE
Menu moves up after clicking on a page on mobile view

### ISSUE THREAD

**Issue by CollActionOfficial** [CollActionteam/collaction_website#67]
On mobile view, make sure the menu moves up again into the burger after clicking on a page. For example, on mobile view, when I click on the burger at the top, the menu appears. When I click on ‘About’, I go to the /about page, but the menu stays visible. Instead, the Menu should move up again such that only the burger is visible (basically as if I clicked the cross button after clicking ‘About’)

**Comment by dastrong** [comment]
@tomsiebring fixed in here (#87) I believe
